#!/bin/bash

# Print and evaluate
evalp()
{
    echo "$@"
    "$@"
}

# Check arguments
if [ ! -d "$1" ]
then
    echo "[ERROR] Must supply binary directory"
    exit 1
fi
# Calculate directories
tool_dir="$1"
native_dir="${tool_dir}-native"
native_final="${tool_dir}-final"
mkdir -p "${native_dir}"
mkdir -p "${native_final}"
# Remove $1
shift;
tool_names="$@"
if [[ "${tool_names}" == "" ]]
then
    echo "[ERROR] No tools specified"
    exit 1
fi

# Generate a native image
jar_file="$tool_dir/fpp.jar"
out_file="$native_dir/fpp"
echo "Building $out_file"
class_path="${CLASSPATH}"
evalp "$GRAALVM_JAVA_HOME/bin/native-image" -H:PageSize=65536 -cp "${class_path}" $FPP_NATIVE_IMAGE_FLAGS \
    --no-fallback --install-exit-handlers \
    -jar "$jar_file" "$out_file"
if [ $? -ne 0 ]
then
    echo "[ERROR] Failed to build $out_file"
    exit 1
fi

for tool in $tool_names
do
    echo "Generating wrapper for fpp-$tool in ${native_final}/fpp-$tool"
    echo '#!/bin/sh
    "`dirname $0`/fpp" '$tool' "$@"' > ${native_final}/fpp-$tool
    chmod +x ${native_final}/fpp-$tool
done

mv "$tool_dir" "$tool_dir.old"
mv "$native_final" "$tool_dir"
